id: P7106E430
initial_creation_type: ocr
source_metadata:
  volumes:
    411d282249df4826aa352782d7ff9fc6:
      base_file: v049.txt
      image_group_id: I1PD95894
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པའི་ཚུལ་གྱི་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1182
      volume_number: 49
